config/routes.rb
FreeTest::Application.routes.draw do
  get "events/index"

  get "events/display"
  
  get "events/new"

  get "events/create"

  get "events/edit"

  get "events/update"

  get "events/show"

  get "events/destroy"

  get "events/intro"

  resources :events do
    member do
      get 'copy'
    end
  end

  root :to => 'events#intro'

end

  

app/models/event.rb
class Event < ActiveRecord::Base
attr_accessible :address, :borough, :days_of_week, :end_date, :name, :start_date, :start_time, :website, :category_id, :notes

  validates_presence_of :name
  validates_presence_of :website
  validates_presence_of :category_id
  validates_presence_of :borough
  validates_presence_of :address
  validates_presence_of :start_date
  validates_length_of :start_date, is:6
  validates_presence_of :end_date
  validates_length_of :end_date, is:6
  validates_presence_of :days_of_week
  
  belongs_to :category

  default_scope order('name ASC')
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :shared_content, :only => [:new, :edit, :display, :copy]
  before_filter :common_content, :only => [:edit, :show, :update, :destroy]

  def shared_content
    @boroughs = ["Manhattan", "Brooklyn", "Queens", "the Bronx", "Staten Island"]
    @notes = ["  ", 
      "Gates open at 6. Bandshell, 9th St. & Prospect Park West.",
      "Gates open at 6:30. Bandshell, 9th St. & Prospect Park West.",
      "Gates open at 3. Bandshell, 9th St. & Prospect Park West.",
      "Gates open at 7. Bandshell, 9th St. & Prospect Park West.",
      "Great Lawn, mid-park between 79th and 85th Streets.",
      "Pier 1: enter the park at Riverside and W. 68th St.",
      "Books at Noon events are standing room only.",
      "Lessons from 6 - 7 pm, followed by dancing to live music 7 - 8:30 pm.",
      "Screening is outdoors on the library steps.",
      "Tickets required, see event website",
      "Movie showing is at the touchdown of the 103rd St. Footbridge.",
      "Doors open 1 hour before show.",
      "Closed on legal holidays.",
      "Movie begins at sunset.", 
      "Live music and food trucks at 6. Movie begins at sundown.",
      "Music starts at 6 pm, movies at sunset.",
      "Gates open at 6:30 pm.",
      "Gates open at 6:30. No chairs. Located on the landscape between Sheep Meadow and the 72nd Street Cross Drive.",
      "Gates open at 6 pm.",
      "Gates open at 7 pm.",
      "The Sculpture Garden opens at 7 pm. In the event of rain, concerts will be held in the Gund Garden Lobby.",
      "RSVP requested - see event website. Doors open at 7:30. Seating is very limited, so arrive early.",
      "Doors open at 6:30.",
      "Gates open at 3 pm.",
      "Free tickets available in advance at the box office, see event website.",
      "Free film tickets are available after 4pm.",
      "Line forms at 5:30 and tickets are distributed at 6, 1 ticket/person.",
      "Line forms at 5 and tickets are distributed at 5:30, 1 ticket/person.",
      "Tickets will be distributed 1 hour in advance, 1 ticket/person.",
      "Pre-screening performances at 7 pm; films begin at sundown.",
      "Outdoors; 3,100 seats - first-come, first-served.",
      "Outdoor screenings of operas; 3,100 seats - first come, first-served.",
      "Films begin at dusk and are open-captioned.",
      "W. 72nd Track & Lawn in Riverside Park. Ground seating 1-2 hours before event.",
      "Approx. 250 chairs plus ground seating.",
      "Doors open at 7pm.",
      "Seating begins at 6:30 on Friday, 7 all other days.",
      "Seating begins at 6:30, movie begins at dusk.",
      "At the Elinor Bunin Munroe Film Center.",
      "Suggested admission of $5.",
      "Admission is pay as you wish.",
      "Free with pay as you wish museum admission.",
      "RSVP recommended - see event website. Free with pay as you wish museum admission.",
      "Admission is pay as you wish from 5:45 - 7:15 pm. The museum closes at 7:45.",
      "Admission is pay as you wish from 11 - 1. The museum closes at 5 pm.",
      "Admission is pay as you wish from 7 - 9:30 pm. The museum closes at 10.",
      "Admission is pay as you wish from 4-5 pm. The aquarium closes at 6.",
      "Admission is pay as you wish from 3-3:30 pm. The aquarium closes at 4:30.",
      "During UNIQLO Free Friday Nights, film tickets are free from 4:00 to 8:00 p.m.",
      "Tickets include access to galleries, exhibitions and films. Closed on Christmas.",
      "Closed on Friday, December 25, 2015.",
      "Closed on Thanksgiving and Christmas Day.",
      "Closed July 4, Thanksgiving and Christmas Day.",
      "Closed Thanksgiving, Christmas and New Year's Day.",
      "Closed on all major holidays.",
      "Free only for those 65 and older, with proof of age if requested.",
      "Free grounds-only admission.",
      "Free grounds-only admission from 9 - 10 am; the grounds close at 6 pm.",
      "No free admission on Saturdays with public programs -Sakura Matsuri, Ghouls & Gourds, etc.",
      "Free hours are suspended during the World Maker Faire.",
      "Doors open at 6; credit card or id required to borrow free headphones; no bags on the dance floor.",
      "Doors open at 1; credit card or id required to borrow free headphones; no bags on the dance floor.",
      "Jerome Ave entrance @ Jerome and Bainbridge; doors open at 4; credit card or id required to borrow free headphones; no bags on the dance floor.",
      "Reservation required; call 212.847.9740 or email event_reservation@amscan.org",
      "RSVPs encouraged - see event website.",
      "RSVP required - see event website.",
      "RSVP required - see event website. Arrive early, seating is not guaranteed.",
      "Tickets required - see event website for details.",
      "Reservation required; go to www.rooftopconcertseries.eventbrite.com",
      "See event website for specific events, times, locations and bookend events from Sept 14 - 21",
      "In the event of rain, the event will be moved indoors at the museum.",
      "Free ticket distribution begins at 4 pm (please check - time is subject to change)."]
  end

  def common_content
    @event = Event.find(params[:id])
  end

  def intro
    @background_image_page = true
    render :layout => 'intro.html.erb'
  end

  def index
    @events = Event.all
  end

  def display
    @background_image_page = true
    @categories = Category.joins(:events).uniq
    @categories_to_choose_from = ["All"]
    x = 0
      while x < @categories.size
        @categories_to_choose_from << @categories[x].name
        x = x+1
      end

    @locations = ["All of NYC", "Manhattan", "Brooklyn", "Queens", "the Bronx", "Staten Island"]
    @default_locations_selected = []
      if params[:locations_selected].class == Array
        @default_locations_selected = params[:locations_selected]
      else @default_locations_selected = @locations[0]
      end
    @default_categories_selected = []
      if params[:categories_selected].class == Array
        @default_categories_selected = params[:categories_selected]
      else @default_categories_selected = @categories_to_choose_from[0]
      end
    @date_range = []

    i = 0
      while i <= 90
        date_label_pair = []
        if i === 0
          date_label_pair << "Today"
        elsif i === 1
          date_label_pair << "Tomorrow"
        else
          date_label_pair << (Date.today+i).strftime("%A, %b %-d")
        end
        date_label_pair << Date.today+i
        @date_range << date_label_pair
        i = i+1
      end

    if params[:date_selected].class != NilClass
      @date_selected = params[:date_selected].to_date
      @day_of_week_selected = @date_selected.strftime ('%w') 
        # Sunday = 0, Monday = 1, etc.

        @locations_selected = params[:locations_selected]

        if @locations_selected[0] === "All of NYC"
          @locations_selected = @boroughs
        end

        @categories_selected = params[:categories_selected]
        if @categories_selected[0] != "All"
          @categories = @categories.where(:name => @categories_selected)
        end
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params[:event])

    if @event.save
        redirect_to @event, notice: "Event created successfully."
    else
        render "new", notice: "Error creating event."
    end
  end

  def edit
  end

  def show
  end

  def update
    if @event.update_attributes(params[:event])
      redirect_to @event, notice: 'Event updated successfully.'
    else
      render "edit", notice: "Error updating event."
      end
  end

  def copy
    @source = Event.find(params[:id])
    @event = @source.dup
    render 'new'
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: 'Event deleted successfully.'
  end

end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
	<p><%= @event.errors.full_messages.first %><p>

	<p><%= f.label :name, "Event name:  " %><%= f.text_field :name  %></p>

	<p><%= f.label :website, "Website, incl. http://  " %><%= f.text_field :website  %></p>

	<p><%= f.label :category_id, "Category:  " %><%= f.select :category_id, options_from_collection_for_select(Category.order("id"), :id, :name, @event.category_id) %></p>

	<p><%= f.label :borough, "Borough:  " %><%= f.select(:borough, options_for_select(@boroughs, @event.borough)) %></p>

	<p><%= f.label :address, "Address:  " %><%= f.text_field :address  %></p>

	<p><%= f.label :start_time, "Time:  " %><%= f.text_field :start_time  %></p>

	<p><%= f.label :start_date,"Start date: yymmdd  "%><%= f.text_field :start_date  %></p>

	<p><%= f.label :end_date, "End date: yymmdd  " %><%= f.text_field :end_date  %></p>

	<p><%= f.label :days_of_week, "Days of week: 0 = Sunday, 1 = Monday, etc.  "%><%= f.text_field :days_of_week  %></p>

	<p><%= f.label :notes, "Notes:  " %><%= f.select(:notes, options_for_select(@notes, @event.notes)) %></p>
	
	<p><%= f.submit %></p>
<% end %>

app/views/events/_formd.html.erb
<%= form_tag("/events/display", method: "get") do %>

  <p>
  <%= label_tag(:date_selected, "Event date:") %>
  <%= select_tag(:date_selected, options_for_select(@date_range, params[:date_selected])) %>
  </p>
  <p>
  <%= label_tag(:locations_selected, "Location(s):") %>
  <%= select_tag(:locations_selected, options_for_select(@locations, @default_locations_selected),{:multiple => true, :size => 3}) %>
  </p>
  <p>
  <%= label_tag(:categories_selected, "Event type(s):") %>
  <%= select_tag(:categories_selected, options_for_select(@categories_to_choose_from, @default_categories_selected),{:multiple => true, :size => 3}) %>
  </p>
  <p><%= submit_tag("Go!") %></p>
<% end %>

app/views/events/display.html.erb
<div id = "display">

<%= render 'formd' %>

<% if @date_selected.class == Date %>
  
    <% @categories.each do |category| %>

        <button type="button"><%= category.name %></button>

        <% x = 0 %>

        <ul>

        <%category.events.each do |event| %>
            
            <% if (@locations_selected.include? event.borough) &&
            (event.days_of_week.include? @day_of_week_selected) &&
            (Date.parse(event.start_date) <= @date_selected) && 
            (Date.parse(event.end_date) >= @date_selected) %>

            <% temp_city = event.borough %>
            <% if temp_city === "Manhattan" %>
            <% then temp_city = "New York" %>
            <% end %>
            
                <div id="listing">
                    <li>
                    <p><%= link_to "#{event.name}", "#{event.website}" %></p>
                    <p><%= "#{event.start_time} " %></p>
                    <p>
                        <% if @locations_selected.length >1 %>
                            <%= "#{event.borough}: " %>
                        <% end %>
                        <%= event.address %>
                    </p>
                    <p><%= event.notes %></p>

                    <p id="directions">
                        <%= link_to "Directions", "http://maps.google.com/maps?daddr=#{event.address}, #{temp_city}, NY" %>
                    </p>
                    </li>
                </div>

                    <% x = x+1 %>
                 
            <% end %>

        <% end %>
        
        <% if x === 0 %>
            <% if category.name.downcase === "other" %>
                <% temp_category = "other events" %>
            <% else temp_category = category.name.downcase %>
            <% end %>
            <li><%= "Sorry, no free #{temp_category} for this date." %></li>
        <% end %>

        </ul>
    <% end %>
<% end %>
</div>

app/views/events/edit.html.erb
<div id="edit">
	<h3>Editing event</h3>

	<%= render 'form' %>

	<%= link_to 'Show', @event %> |
	<%= link_to 'Back to index', events_path %>
</div>

app/views/events/index.html.erb

<p><%= notice %></p>

<%= link_to "Enter new event", new_event_path %>

<h3>Event Index</h3> 

<table>
    <thead>
        <th>Event</th>
        <th>Cat</th>
        <th>Borough</th>
        <th>Address</th>
        <th>Time</th>
        <th>Start Date</th>
        <th>End date</th>  
        <th></th>
        <th></th>
        <th></th>
    </thead>
    <tbody>
<% @events.each do |event| %>

    <% temp_city = event.borough %>
            <% if temp_city === "Manhattan" %>
            <% then temp_city = "New York" %>
            <% end %>


        <tr>
            <td><%= link_to "#{event.name}", "#{event.website}" %></td>
            <td><%= event.category_id %></td>
            <td><%= event.borough %></td>
            <td><%= event.address %></td>
            <td><%= event.start_time %></td>
            <td><%= event.start_date %></td>
            <td><%= event.end_date %></td>
            <td><%= link_to 'Edit', edit_event_path(event) %></td>
            <td><%= link_to 'Copy', copy_event_path(event) %></td>
            <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>

<% end %>
    </tbody>
</table>
<br>
<%= link_to "Enter new event", new_event_path %>

app/views/events/intro.html.erb
<div id="main">
<p> Free in the City || NYC is the easy way to find free entertainment and cultural events in NYC.</p>
<break>
<p>Use the select boxes to specify the:</p>
<break>
	<ol>
		<li>Event date: You can view free events for the next 90 days.</li>
		<li>Event location: Select "All of NYC" to see the 5 boroughs or specify 1 or more boroughs.</li> 
		<li>Event type: Select "All" or specify 1 or more event types.</li>
	</ol>
<p>Then click Go! and free events that match your request will be listed below.  Click on the event name to link directly to the event website for the most current information.</p>
<p id="intro"><%= link_to "Get Started", "events/display" %>
</p>
</div>

app/views/events/new.html.erb
<h3><%= notice %></h3>

<h3>Enter a new event:</h3>

<%= render 'form' %>

app/views/events/show.html.erb
<div id="show">
	<p><%= notice %></p>

	<p><%= @event.name %></p>
	<p><%= @event.website %></p>
	<p><%= @event.category_id %></p>
	<p><%= @event.borough %></p>
	<p><%= @event.address %></p>
	<p><%= @event.start_time %></p>
	<p><%= @event.start_date %></p>
	<p><%= @event.end_date %></p>
	<p><%= @event.days_of_week %></p>
	<p><%= @event.notes %></p>

	<%= link_to "Back to index", events_path %>
	<br>
	<br>
	<%= link_to "Edit event", edit_event_path(@event) %>
</div>